# Generated by Django 4.2.4 on 2023-08-19 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('product_name', models.CharField(max_length=50)),
                ('contract_number', models.CharField(max_length=50, unique=True)),
                ('date_of_contract', models.CharField(max_length=50)),
            ],
            options={
                'unique_together': {('company_name', 'product_name')},
            },
        ),
    ]
