# Generated by Django 4.2.4 on 2023-08-19 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='contract_photo',
            field=models.FileField(null=True, upload_to='uploads/%company_name/%product_name'),
        ),
    ]
