# Generated by Django 4.2.4 on 2023-08-07 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='data_of_contract',
            field=models.DateField(),
        ),
    ]
