# Generated by Django 4.2.4 on 2023-08-15 17:48

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_alter_assessment_data_of_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='data_of_contract',
            field=django_jalali.db.models.jDateField(),
        ),
    ]
