# Generated by Django 4.2.4 on 2023-09-02 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_contract_address_contract_approved_discount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phaseonefiles',
            old_name='ducuments',
            new_name='documents',
        ),
    ]
