# Generated by Django 4.2.4 on 2023-08-20 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_alter_assessment_contract_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentphoto',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
