# Generated by Django 4.2.4 on 2023-08-16 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0003_alter_assessment_data_of_contract'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assessment',
            old_name='data_of_contract',
            new_name='date_of_contract',
        ),
    ]
