# Generated by Django 4.2.4 on 2023-09-03 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0003_rename_ducuments_phaseonefiles_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractphoto',
            name='photo',
            field=models.ImageField(upload_to='uploads/contracts_first_page_photo/'),
        ),
        migrations.CreateModel(
            name='PhaseOneDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documents', models.FileField(upload_to='uploads/first_phase_final_documents/')),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='assessment.contract')),
            ],
        ),
    ]
