# Generated by Django 4.2.4 on 2023-08-19 08:08

import assessment.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0003_alter_assessment_contract_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='contract_photo',
            field=models.ImageField(null=True, upload_to=assessment.models.path_and_rename),
        ),
    ]
