# Generated by Django 4.2.4 on 2023-09-03 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0004_alter_contractphoto_photo_phaseonedocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhaseTwoDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documents', models.FileField(upload_to='uploads/second_phase_documents/')),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='assessment.contract')),
            ],
        ),
        migrations.RenameModel(
            old_name='SupplementFiles',
            new_name='SupplementDocument',
        ),
        migrations.RemoveField(
            model_name='phasetwofiles',
            name='contract',
        ),
        migrations.AlterField(
            model_name='phaseonedocument',
            name='documents',
            field=models.FileField(upload_to='uploads/first_phase_documents/'),
        ),
        migrations.DeleteModel(
            name='PhaseOneFiles',
        ),
        migrations.DeleteModel(
            name='PhaseTwoFiles',
        ),
    ]
