# Generated by Django 4.2.4 on 2023-08-18 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0004_rename_data_of_contract_assessment_date_of_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='date_of_contract',
            field=models.DateField(),
        ),
    ]
