# Generated by Django 4.2.4 on 2023-09-04 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0005_phasetwodocument_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='product_category',
            field=models.CharField(choices=[('IT', 'فناوری اطلاعات'), ('SCADA', 'کنترل صنعتی و اسکادا')], max_length=5, null=True),
        ),
    ]
