# Generated by Django 4.2.4 on 2023-08-18 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0005_alter_assessment_date_of_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='contract_number',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='assessment',
            unique_together={('company_name', 'product_name')},
        ),
    ]
