# Generated by Django 4.2.4 on 2023-09-05 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0006_contract_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='date_of_contract',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
